Fix patient search indexing for race and ethnicity.
synthetichealth/candle pull request #4
Opened 2018-06-20 19:56 UTC by jawalonoski

Bonus, update outdated dependencies and have unit tests use configuration settings for DB.

2018-06-20 21:17 UTC, eedrummer requested changes

2018-06-20 21:17 UTC, eedrummer commented on test/test_helper.rb
>  require './lib/config'
This line should now be removed since you added it in line 5

2018-06-21 11:50 UTC, jawalonoski commented on test/test_helper.rb
>  require './lib/config'
Done.

2018-06-21 13:10 UTC, eedrummer approved these changes

2018-06-21 13:10 UTC, merged